iiab_magnet:
    resource: "@IIABMagnetBundle/Controller/"
    type:     annotation
    prefix:   /

iiab_audit:
    resource: "@IIABAuditBundle/Controller/"
    type:     annotation
    prefix:   /admin

shared_bundle:
    resource: "@lfSharedDataBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin
    options: { i18n: false }

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
    options: { i18n: false }
