parameters:
  submission_data_reserved_keys:
    - 'admin_email'
    - 'admin_name'
    - 'calculated_gpa'
    - 'Committee Review Score - First Choice'
    - 'Committee Review Score - Second Choice'
    - 'Committee Review Score - Third Choice'
    - 'conduct_eligible'
    - 'conduct_gpa'
    - 'counselor_email'
    - 'english_teacher_email'
    - 'english_teacher_name'
    - 'first_choice_assessment_test_eligible'
    - 'first_choice_assessment_test_score'
    - 'audition_1'
    - 'audition_2'
    - 'audition_total'
    - 'first_choice_course_eligibility_met'
    - 'first_choice_first_choice_focus'
    - 'first_choice_first_choice_focus_extra_1'
    - 'first_choice_first_choice_focus_extra_2'
    - 'first_choice_first_choice_focus_extra_3'
    - 'first_choice_first_choice_focus_score'
    - 'first_choice_second_choice_focus'
    - 'first_choice_second_choice_focus_extra_1'
    - 'first_choice_second_choice_focus_extra_2'
    - 'first_choice_second_choice_focus_extra_3'
    - 'first_choice_second_choice_focus_score'
    - 'first_choice_third_choice_focus'
    - 'first_choice_third_choice_focus_extra_1'
    - 'first_choice_third_choice_focus_extra_2'
    - 'first_choice_third_choice_focus_extra_3'
    - 'first_choice_third_choice_focus_score'
    - 'homeroom_teacher_email'
    - 'homeroom_teacher_name'
    - 'learner_screening_device_url'
    - 'math_teacher_email'
    - 'math_teacher_name'
    - 'math_test'
    - 'orientation'
    - 'parent_employment'
    - 'parent_employee_name'
    - 'parent_employee_location'
    - 'reading_teacher_email'
    - 'reading_teacher_name'
    - 'reading_test'
    - 'recommendation_counselor_comments'
    - 'recommendation_counselor_disciplineInfractions'
    - 'recommendation_counselor_overall_recommendation'
    - 'recommendation_counselor_plan504'
    - 'recommendation_counselor_planGEP'
    - 'recommendation_counselor_planIEP'
    - 'recommendation_counselor_support_file_504'
    - 'recommendation_counselor_url'
    - 'recommendation_english_url'
    - 'recommendation_math_initiative'
    - 'recommendation_math_overall_recommendation'
    - 'recommendation_math_url'
    - 'science_teacher_email'
    - 'science_teacher_name'
    - 'second_choice_assessment_test_eligible'
    - 'second_choice_assessment_test_score'
    - 'second_choice_combined_audition_score'
    - 'second_choice_course_eligibility_met'
    - 'second_choice_first_choice_focus'
    - 'second_choice_first_choice_focus_extra_1'
    - 'second_choice_first_choice_focus_extra_2'
    - 'second_choice_first_choice_focus_extra_3'
    - 'second_choice_first_choice_focus_score'
    - 'second_choice_second_choice_focus'
    - 'second_choice_second_choice_focus_extra_1'
    - 'second_choice_second_choice_focus_extra_2'
    - 'second_choice_second_choice_focus_extra_3'
    - 'second_choice_second_choice_focus_score'
    - 'second_choice_third_choice_focus'
    - 'second_choice_third_choice_focus_extra_1'
    - 'second_choice_third_choice_focus_extra_2'
    - 'second_choice_third_choice_focus_extra_3'
    - 'second_choice_third_choice_focus_score'
    - 'social studies_teacher_email'
    - 'social studies_teacher_name'
    - 'student_email'
    - 'teacher'
    - 'third_choice_assessment_test_eligible'
    - 'third_choice_assessment_test_score'
    - 'third_choice_combined_audition_score'
    - 'third_choice_course_eligibility_met'
    - 'third_choice_first_choice_focus'
    - 'third_choice_first_choice_focus_extra_1'
    - 'third_choice_first_choice_focus_extra_2'
    - 'third_choice_first_choice_focus_extra_3'
    - 'third_choice_first_choice_focus_score'
    - 'third_choice_second_choice_focus'
    - 'third_choice_second_choice_focus_extra_1'
    - 'third_choice_second_choice_focus_extra_2'
    - 'third_choice_second_choice_focus_extra_3'
    - 'third_choice_second_choice_focus_score'
    - 'third_choice_third_choice_focus'
    - 'third_choice_third_choice_focus_extra_1'
    - 'third_choice_third_choice_focus_extra_2'
    - 'third_choice_third_choice_focus_extra_3'
    - 'third_choice_third_choice_focus_score'
    - 'writing_prompt'
    - 'writing_sample'
    - 'recommendation_conselor'
    - 'recommendation_conselor_url'
    - 'recommendation_counselor_attendance'
    - 'recommendation_counselor_comments'
    - 'recommendation_counselor_disciplineInfractions'
    - 'recommendation_counselor_maturity'
    - 'recommendation_counselor_overall_recommendation'
    - 'recommendation_counselor_peerInteraction'
    - 'recommendation_counselor_plan504'
    - 'recommendation_counselor_planGEP'
    - 'recommendation_counselor_planIEP'
    - 'recommendation_counselor_support_file_504'
    - 'recommendation_counselor_url'
    - 'recommendation_counselor_workEthic'
    - 'recommendation_english'
    - 'recommendation_english_url'
    - 'recommendation_math'
    - 'recommendation_math_class_assignments'
    - 'recommendation_math_comments'
    - 'recommendation_math_communication'
    - 'recommendation_math_confidence'
    - 'recommendation_math_curiosity'
    - 'recommendation_math_homework'
    - 'recommendation_math_initiative'
    - 'recommendation_math_loves_learning'
    - 'recommendation_math_new_concepts'
    - 'recommendation_math_overall_recommendation'
    - 'recommendation_math_recall'
    - 'recommendation_math_responsibility'
    - 'recommendation_math_self_correcting'
    - 'recommendation_math_unique_conclusions'
    - 'recommendation_english_class_assignments'
    - 'recommendation_english_comments'
    - 'recommendation_english_communication'
    - 'recommendation_english_confidence'
    - 'recommendation_english_curiosity'
    - 'recommendation_english_homework'
    - 'recommendation_english_initiative'
    - 'recommendation_english_loves_learning'
    - 'recommendation_english_new_concepts'
    - 'recommendation_english_overall_recommendation'
    - 'recommendation_english_recall'
    - 'recommendation_english_responsibility'
    - 'recommendation_english_self_correcting'
    - 'recommendation_english_unique_conclusions'
    - 'learner_profile_url'
    - 'learner_screening_device_abstract_thinking'
    - 'learner_screening_device_citizenship'
    - 'learner_screening_device_creative_thinking'
    - 'learner_screening_device_cultural'
    - 'learner_screening_device_general_intellect'
    - 'learner_screening_device_leadership'
    - 'learner_screening_device_performing_arts'
    - 'learner_screening_device_psychomotor'
    - 'learner_screening_device_url'
    - 'learner_screening_device_visual_arts'
    - 'odr_1'
    - 'odr_2'
    - 'odr_3'
    - 'student_profile_score'
    - 'student_profile_percentage'
    - 'holistic_committee'
    - 'choice_zone'


