<?php

namespace LeanFrog\SharedDataBundle\Repository;

/**
 * AcademicYearDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AcademicYearDataRepository extends \Doctrine\ORM\EntityRepository
{
}
