<?php

namespace LeanFrog\SharedDataBundle\Repository;

/**
 * CapacityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CapacityRepository extends \Doctrine\ORM\EntityRepository
{
}
