<?php

namespace LeanFrog\SharedDataBundle\Repository;

/**
 * PopulationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PopulationRepository extends \Doctrine\ORM\EntityRepository
{
}
