<?php

namespace LeanFrog\SharedDataBundle\Repository;

/**
 * ProgramSchoolDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProgramSchoolDataRepository extends \Doctrine\ORM\EntityRepository
{
}
