<?php

namespace LeanFrog\SharedDataBundle\Repository;

/**
 * ProgramSchoolRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProgramSchoolRepository extends \Doctrine\ORM\EntityRepository
{
}
