<?php

namespace LeanFrog\SharedDataBundle\Repository;

/**
 * StudentDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StudentDataRepository extends \Doctrine\ORM\EntityRepository
{
}
