<?php

namespace LeanFrog\SharedDataBundle\Repository;

/**
 * StudentGradeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StudentGradeRepository extends \Doctrine\ORM\EntityRepository
{
}
