<?php
/**
 * Company: Image In A Box
 * Date: 9/30/15
 * Time: 2:47 PM
 * Copyright: 2015
 */

namespace IIAB\MagnetBundle\Form\Type;


use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class AddressBoundSchoolUpdateType extends AbstractType {

	/**
	 * {@inheritdoc}
	 */
	public function buildForm( FormBuilderInterface $builder , array $options ) {

		$builder->add( 'schools' , 'collection' , [ 
			'label' => false , 
			'entry_type' => AddressBoundSchoolType::class
		] );
		$builder->add( 'save' , 'submit' , [ 'label' => 'Updated Schools' ] );
	}

	/**
	 * {@inheritdoc}
	 */
	public function setDefaultOptions( OptionsResolverInterface $resolver ) {

		parent::setDefaultOptions( $resolver ); // TODO: Change the autogenerated stub
	}

	public function getName() {

		return 'address_bound_school_update';
	}
}