<?php

namespace IIAB\MagnetBundle\Repository;

/**
 * AddressBoundEnrollmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AddressBoundEnrollmentRepository extends \Doctrine\ORM\EntityRepository
{
}
